spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petshop?serverTimezone=America/Sao_Paulo
    username: petshop
    password: petshop
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      show-sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update